import {isAdmin} from '@/lib/auth';
import {publicContent} from '@/lib/public-content';
import {collectionStructuredData} from '@/lib/collection-schema';
import {notFound} from 'next/navigation';
import {listHubs,listProducts,listStartingProducts,listPosts,origin} from '@/lib/db';
import {ContentBody,ImageCredit} from '@/components/site/editorial';
import {ProductPostcards,ProductInsights} from '@/components/site/product-postcards';
import {PageTaxonomy} from '@/components/site/page-taxonomy';
import {belongsToHub,primaryProduct} from '@/lib/content-graph';
import {jsonLd} from '@/lib/seo';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const stored=(await listHubs(true)).find(p=>p.slug===slug);const h=stored&&(stored.content.generationState!=='planned'||await isAdmin())?{...stored,content:publicContent(stored.content)}:undefined;return h?{title:{absolute:h.content.seoTitle},description:h.content.seoDescription,alternates:{canonical:`/collections/${h.slug}`},robots:h.status==='published'?undefined:{index:false,follow:false}}:{title:'Page not found',robots:{index:false}};}
export default async function Collection({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const stored=(await listHubs(true)).find(p=>p.slug===slug);const h=stored&&(stored.content.generationState!=='planned'||await isAdmin())?{...stored,content:publicContent(stored.content)}:undefined;if(!h)notFound();const [products,posts,hubs]=await Promise.all([h.status==='draft'?listStartingProducts():listProducts(),listPosts(),listHubs()]);const articleParents=new Set(posts.filter(p=>belongsToHub(p,h)).map(primaryProduct));const items=products.filter(p=>belongsToHub(p,h)||h.content.relatedProducts.includes(p.slug)||articleParents.has(p.slug));const memberSlugs=new Set(items.map(i=>i.slug));const articles=posts.filter(p=>belongsToHub(p,h)||memberSlugs.has(primaryProduct(p))).slice(0,6);const children=hubs.filter(p=>p.content.parentHub===slug);const parent=hubs.find(p=>p.slug===h.content.parentHub);const crumbs=[{name:'Collections',item:origin()+'/collections'},...(parent?[{name:parent.title,item:origin()+`/collections/${parent.slug}`}]:[]),{name:h.title,item:origin()+`/collections/${h.slug}`}];return <main id="main" className="managed-insight category-landing"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(collectionStructuredData(h,items,origin()))}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:crumbs.map((c,i)=>({'@type':'ListItem',position:i+1,...c}))})}}/>{h.status==='draft'&&<div className="draft-preview-bar">Draft preview · excluded from search indexing</div>}<section className="section article-hero"><nav className="breadcrumbs"><a href="/collections">Collections</a>{parent&&<><span>/</span><a href={`/collections/${parent.slug}`}>{parent.title}</a></>}<span>/</span><span>{h.title}</span></nav><span className="eyebrow">{h.content.categoryScope?.market||h.content.pageType}</span><h1>{h.title}</h1><p>{h.summary}</p><div className="category-counts"><span><b>{items.length}</b> products</span><span><b>{articles.length}</b> published Insights</span></div>{h.image&&<figure className="article-image"><img src={h.image} alt={h.content.imageAlt||h.title}/><ImageCredit credit={h.imageCredit}/></figure>}</section>{children.length>0&&<nav className="category-children" aria-label="Subcategories">{children.map(c=><a key={c.id} href={`/collections/${c.slug}`}>{c.title}<span>{products.filter(i=>belongsToHub(i,c)).length}</span></a>)}</nav>}<PageTaxonomy content={h.content}/><ProductPostcards items={items} title={`${h.title} products`} eyebrow="EXPLORE THE COLLECTION"/>{items.some(i=>i.status==='draft')&&<p className="category-preview-note">Cards marked Preview are draft product pages available for review. They are excluded from search indexing.</p>}<section className="section category-editorial"><ContentBody content={h.content} products={items}/></section><ProductInsights posts={articles} name={h.title}/></main>;}
