import styles from './home.module.css';
import {HomeHero} from '@/components/site/home-hero';
import {listProducts,listPosts,origin} from '@/lib/db';
import {jsonLd} from '@/lib/seo';
import {Catalog} from '@/components/site/catalog';
import {catalogCard} from '@/lib/catalog-card';
import {PostCard,SourcingCTA} from '@/components/site/editorial';
import {selectHomepagePosts} from '@/lib/journal';
export const dynamic='force-dynamic';
export const metadata={alternates:{canonical:'/'}};
export default async function Home(){const [products,posts]=await Promise.all([listProducts(),listPosts()]);const journalPosts=selectHomepagePosts(posts,crypto.randomUUID());return <main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'Organization',name:'Rarewood Exchange',url:origin(),parentOrganization:{'@type':'Organization',name:'AdvGuides, LLC'}})}}/><HomeHero/><section className={`section ${styles.directory}`} id="products"><div className="section-heading"><div><span className="eyebrow">THE WOOD CATALOG</span><h2>Start with what you need.</h2></div><p>Exotic hardwoods, distinctive slabs, decking, flooring, and panels. Browse by product or start with a species.</p></div><Catalog items={products.map(catalogCard)} compact/></section><section className="how-section"><div className="how-intro"><span className="eyebrow">LESS BACK AND FORTH</span><h2>Good sourcing<br/>starts with<br/><span>good context.</span></h2><a className="button outline" href="/about#how-it-works">How it works</a></div><div className="how-steps">{[['01','Find your wood','Understand the material forms and dimensions before starting your request.'],['02','Share the requirements','Tell us your volume, specifications, delivery point, and purchasing timeline.'],['03','Start the conversation','Your inquiry is saved for review and assignment to a lumber supplier.']].map(([n,t,p])=><div key={n}><span className="step-number">{n}</span><h3>{t}</h3><p>{p}</p></div>)}</div></section><section className="section"><div className="section-heading"><div><span className="eyebrow">THE SOURCING JOURNAL</span><h2>A little context goes a long way.</h2></div><a className="button outline" href="/insights">View the journal</a></div><div className="posts-grid">{journalPosts.map((r,i)=><PostCard post={r} index={i} key={r.id}/>)}</div></section><SourcingCTA/></main>}
