import catalog from '../data/imported-catalog.json';
import taxonomy from '../data/catalog-taxonomy.json';
import {categories,type Post} from './types';
import {categorySlug,type CategoryScope} from './content-graph';
const scopes=new Map<string,CategoryScope>();
for(const market of taxonomy.markets){const scope={market:market.market};scopes.set(categorySlug(scope),scope);for(const cat of market.categories){const s={market:market.market,category:cat.category};scopes.set(categorySlug(s),s);}}
for(const item of catalog)for(const scope of item.placements)scopes.set(categorySlug(scope),scope);

export const categorySeeds:Post[]=[...scopes].map(([slug,scope])=>{const title=scope.category||scope.market;const context=scope.market&&scope.category?`${scope.market.toLowerCase()} ${scope.category.toLowerCase()}`:title.toLowerCase();const summary=`Explore ${context} for specialty wood sourcing. Compare wood forms and order requirements and use the linked buyer guides to prepare a specific quote request.`;return {id:`hub-${slug}`,slug,title,category:scope.market||'Product categories',summary,image:'',imageCredit:'',status:'published',createdAt:'2026-10-07T00:00:00.000Z',updatedAt:'2026-10-07T00:00:00.000Z',content:{pageType:'category',categoryScope:scope,...(scope.market&&scope.category?{parentHub:categorySlug({market:scope.market})}:{}),seoTitle:`${title}${scope.market&&scope.category?` for ${scope.market}`:''} | Rarewood Exchange`,seoDescription:summary.slice(0,200),sections:[{heading:`Source ${title.toLowerCase()} with a clear requirement`,paragraphs:[`Use this collection to find relevant product pages. Each page brings together product information, supporting Insights, and a sourcing request for that specific product.`,`Compare the intended application, required grade, documentation, volume, and receiving setup. Availability and commercial terms are confirmed by the broker handling your request.`]}],applications:[],buyingChecklist:[],faqs:[],relatedProducts:[],sourceNotes:''}};});
