import products from '@/data/wood-products.json';
import type {Product,Post,Content} from './types';
export const seedProducts=products as Product[];
const date='2026-10-07T17:43:00.000Z';
function article(slug:string,title:string,summary:string,parent:string,sections:Content['sections']):Post{return {id:'journal-'+slug,slug,title,summary,category:'Wood buying guide',image:'',imageCredit:'',status:'published',createdAt:date,updatedAt:date,content:{pageType:'article',primaryProduct:parent,seoTitle:title+' | Rarewood Exchange',seoDescription:summary,sections,applications:[],buyingChecklist:[],faqs:[],relatedProducts:[parent],sourceNotes:'',generationState:'ready',tags:['Wood sourcing'],topics:['Planning a lumber order']}};}
export const seedPosts:Post[]=[
article('ipe-decking-order-details','Ipe decking: the details that make an order usable','Specify board dimensions, edge profile and length mix before comparing decking quotes.','ipe-decking',[
 {heading:'Start with the board schedule',paragraphs:['An Ipe decking request needs more than a square-foot total. The board width, thickness and required lengths determine which material fits the deck layout. Give the supplier a length schedule where one exists, and distinguish fixed lengths from lengths you can cut on site.','Keep nominal sizing separate from actual finished dimensions. Ask for the measured width and thickness of the offered boards before finalizing the layout or fastening plan.']},
 {heading:'Match the edge to the fastening plan',paragraphs:['Square-edge and grooved decking are different order requirements. Describe the planned fasteners and the edge profile they require. An assumption about grooves or machining can result in boards that need additional work before installation.']},
 {heading:'Compare the same scope',paragraphs:['Compare quotes using the same dimensions, total quantity, length mix and delivery destination. State whether trim, fascia or other related pieces belong in the request. Ask the supplier to identify the material condition and any excluded services in writing.','Finish the brief with a destination ZIP, receiving access and target arrival window. The material offer and freight arrangement should describe the same order.']}
]),
article('choosing-a-live-edge-slab','Choosing a live-edge slab for a specific space','Look beyond the widest measurement: usable area, thickness and condition shape a slab project.','jatoba-slabs',[
 {heading:'Measure the usable shape',paragraphs:['A live-edge slab is not a rectangular board. Its narrowest width, edge curves and any areas you plan to remove determine the usable surface. Bring the supplier the dimensions of the finished table or countertop and identify where the shape can vary.']},
 {heading:'Review both faces',paragraphs:['Ask for photographs of both faces, the ends and visible checks. Request measurements with the piece clearly identified, so a conversation about a particular slab remains tied to that piece. Natural edges, voids and grain variation may be part of the design, but they should be visible before you accept an offer.']},
 {heading:'Account for preparation and delivery',paragraphs:['Clarify whether the slab is rough, flattened, sanded or finished. The current thickness and the required finished thickness are separate measurements. Have your fabricator assess what preparation is needed for the intended design.','Delivery planning should use the packaged dimensions and weight. Describe the unloading equipment and the route into the workspace before freight is booked.']}
]),
article('plywood-quote-specifications','Plywood quotes: specify the whole panel','Face species, core, thickness and finish belong together when comparing a plywood offer.','birch-plywood',[
 {heading:'The face name is only one specification',paragraphs:['A request for birch plywood does not define the panel construction, sheet dimensions or face finish. State the intended use and the features that matter to it: visible faces, exposed edges, machining and the finish you plan to apply.']},
 {heading:'Keep dimensions and construction explicit',paragraphs:['Include actual thickness and sheet size. Ask the supplier to identify the core construction and the face and back grades of the offered panel. If a branded construction, documented performance or a particular origin is required, make that an explicit requirement rather than assuming it from a trade name.']},
 {heading:'Price usable material',paragraphs:['For partial sheets or surplus lots, record each panel size and disclosed damage. An inexpensive sheet may not provide the required yield when cut to the project dimensions. Share a cut list when possible and compare the amount of usable material.','Ask how panels will be protected in transit and how the package will be unloaded. Keep packaging and delivery charges attached to the material quote.']}
])];
