import { z } from 'zod';
export const slugSchema=z.string().min(2).max(120).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
export const blogTopicSchema=z.object({slug:slugSchema,title:z.string().min(10).max(150),intent:z.enum(['specification','application','logistics']),targetKeyword:z.string().min(3).max(150),brief:z.string().min(30).max(1200)});
export const blogTopicsSchema=z.array(blogTopicSchema).length(3).superRefine((topics,ctx)=>{for(const key of ['slug','title','targetKeyword','intent'] as const){if(new Set(topics.map(t=>t[key].trim().toLowerCase())).size!==3)ctx.addIssue({code:z.ZodIssueCode.custom,message:`The three topics must have different ${key} values.`,path:[key]});}});
const pair=z.object({title:z.string().max(150),text:z.string().max(2000)});
export const landingSchema=z.object({displayName:z.string().max(150),badges:z.array(z.string().max(100)).max(4),facts:z.array(z.object({value:z.string().max(80),label:z.string().max(150)})).max(4),highlights:z.array(z.string().max(500)).max(6),overview:z.array(z.string().max(4000)).max(4),benefits:z.array(pair).max(6),specifications:z.object({caption:z.string().max(300),columns:z.array(z.string().max(100)).max(5),rows:z.array(z.array(z.string().max(500)).max(5)).max(20),note:z.string().max(2000)}),applications:z.array(pair).max(12),shipping:z.array(pair).max(6),related:z.array(slugSchema).max(12),faqs:z.array(z.object({question:z.string().max(300),answer:z.string().max(2000)})).max(12)});
export const contentSchema=z.object({speciesSlug:slugSchema.optional(),wood:z.object({form:z.string().max(80),unit:z.string().max(40),availability:z.string().max(50)}).optional(),generationState:z.enum(['planned','ready']).optional(),insightPlan:blogTopicSchema.optional(),publicationMode:z.enum(['preapproved','preapproved-batch']).optional(),publishedAt:z.string().datetime().optional(),sourceNotesResetVersion:z.literal(1).optional(),research:z.object({retrievedAt:z.string().datetime(),summary:z.string().min(100).max(24000),sources:z.array(z.object({id:z.number().int().positive().max(20),url:z.string().max(2000).url().refine(v=>/^https?:\/\//.test(v)),title:z.string().max(300)})).min(2).max(20)}).optional(),brokerAvailabilityConfirmed:z.boolean().optional(),brokerAvailabilityNote:z.string().max(1000).optional(),blogTopics:blogTopicsSchema.optional(),sourceTopicSlug:slugSchema.optional(),categoryScope:z.object({market:z.string().max(80),category:z.string().max(120).optional()}).optional(),primaryProduct:slugSchema.optional(),tags:z.array(z.string().min(1).max(80)).max(30).optional(),topics:z.array(z.string().min(1).max(80)).max(30).optional(),hubSlugs:z.array(slugSchema).max(30).optional(),pageType:z.enum(['article','tag','topic','category']).optional(),parentHub:slugSchema.optional(),imageAlt:z.string().max(300).optional(),customLayout:z.boolean().optional(),landingProfile:landingSchema.optional(),seoTitle:z.string().min(5).max(100),seoDescription:z.string().min(20).max(200),sections:z.array(z.object({heading:z.string().min(2).max(180),paragraphs:z.array(z.string().min(5).max(4000)).min(1).max(8)})).min(1).max(16),applications:z.array(z.string().max(150)).max(20),buyingChecklist:z.array(z.string().max(500)).max(20),faqs:z.array(z.object({question:z.string().min(3).max(300),answer:z.string().min(5).max(2000)})).max(12),relatedProducts:z.array(slugSchema).max(12),sourceNotes:z.string().max(16000),aliases:z.array(z.string().max(150)).max(30).optional(),catalogPlacements:z.array(z.object({market:z.string().max(80),category:z.string().max(120)})).max(20).optional(),sourceStatus:z.enum(['current','proposed']).optional(),needsClarification:z.boolean().optional(),generatedAt:z.string().optional(),reviewedAt:z.string().optional()});
export const recordSchema=z.object({kind:z.enum(['product','post']),id:z.string().max(80).optional(),slug:slugSchema,name:z.string().min(2).max(150),category:z.string().min(2).max(80),summary:z.string().min(10).max(500),content:contentSchema,image:z.string().max(2000).default(''),imageCredit:z.string().max(600).default(''),status:z.enum(['draft','published']).default('draft'),reviewed:z.boolean().optional()});
export const leadSchema=z.object({requestKey:z.string().uuid(),product:z.string().trim().min(2).max(300),company:z.string().trim().min(2).max(200),name:z.string().trim().min(2).max(150),email:z.string().trim().email().max(254),phone:z.string().max(80).default(''),volume:z.coerce.number().positive().max(10000000),unit:z.enum(['Board feet','Linear feet','Square feet','Sheets','Slabs','Pieces','Truckloads']),frequency:z.enum(['One-time purchase','Monthly','Quarterly','Annual program']),grade:z.string().trim().min(2).max(300),application:z.string().trim().min(2).max(200),destination:z.string().trim().min(3).max(300),timing:z.enum(['As soon as available','Within 30 days','1–3 months','Planning ahead']),dimensions:z.string().max(500).default(''),receiving:z.string().max(500).default(''),packaging:z.string().max(150).default(''),details:z.string().max(4000).default(''),website:z.string().max(300).default(''),consent:z.literal(true),contactFax:z.string().max(100).default('')});
export function slugify(s:string){return s.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120);}
