'use client';
import {useEffect,useState} from 'react';
import {LockKeyhole,Copy,ExternalLink} from 'lucide-react';
import type {BrokerReviewAccessInfo} from '@/lib/broker-review-types';
export function BrokerReviewAccess(){
 const [access,setAccess]=useState<BrokerReviewAccessInfo|null>(null),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function request(action?:string){const r=await fetch('/api/broker-review/access',action?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})}:{cache:'no-store'});const data=await r.json() as BrokerReviewAccessInfo&{token?:string;error?:string};if(!r.ok)throw new Error(data.error||'Unable to manage the review link.');return data;}
 useEffect(()=>{request().then(setAccess).catch(cause=>setError(cause.message));},[]);
 async function change(action:'create'|'revoke'){
  if(access?.active&&!window.confirm(action==='revoke'?'Disable the broker’s review link? Saved answers will remain.':'Replace the current review link? The old link will stop working. Saved answers will remain.'))return;
  setBusy(true);setError('');setNotice('');try{const data=await request(action);setAccess(data);setUrl(data.token?`${window.location.origin}/broker/products#access=${data.token}`:'');setNotice(action==='create'?'Copy this private link now and share it directly with the supplier.':'Broker access disabled. Saved answers are unchanged.');}catch(cause){setError(cause instanceof Error?cause.message:'Please try again.');}finally{setBusy(false);}
 }
 return <section className="publisher-batch broker-review-access"><h3><LockKeyhole size={17}/> Broker availability review</h3><p>the supplier can answer Yes or No at his own pace. Yes moves a product into Drafts; No keeps it here.</p><a className="button outline" href="/broker/products" target="_blank" rel="noreferrer"><ExternalLink size={15}/> Open review checklist</a>{access&&<><small>{access.active?`Private link active until ${new Date(access.expiresAt!).toLocaleDateString()}`:'No active broker link'}</small><button className="button dark" disabled={busy} onClick={()=>void change('create')}>{busy?'Saving…':access.active?'Replace private link':'Create private link'}</button>{access.active&&<button className="button outline" disabled={busy} onClick={()=>void change('revoke')}>Disable link</button>}</>}{url&&<label className="field"><span>Private review link · anyone with it can answer</span><input aria-label="Private broker review link" readOnly value={url} onFocus={event=>event.target.select()}/><button className="button outline" onClick={()=>navigator.clipboard.writeText(url).then(()=>setNotice('Private link copied.')).catch(()=>setError('Select the link above and copy it manually.'))}><Copy size={15}/> Copy link</button></label>}{notice&&<p role="status">{notice}</p>}{error&&<p className="form-error" role="alert">{error}</p>}<small>Only product availability is shared. This link does not grant access to leads or the admin.</small></section>;
}
