'use client';
import {useState} from 'react';
import {Search,Trees,Layers,SquareStack,Logs,Sprout,SlidersHorizontal} from 'lucide-react';
import {IllustrationImage} from './illustration-image';
import {productIllustrations} from '@/lib/product-illustrations';
import illustrationStyles from './product-artwork.module.css';
import type {CatalogCard} from '@/lib/catalog-card';
export function CategoryIcon({category,size=25}:{category:string;size?:number}){const Icon=category==='Exotic lumber'?Trees:category==='Slabs & rounds'?Logs:category==='Plywood & panels'?SquareStack:Layers;return <Icon size={size} strokeWidth={1.5}/>}
export function ProductCard({item}:{item:CatalogCard}){const markets=[...new Set((item.content.catalogPlacements||[]).map(p=>p.market))];return <a className="product-card" href={`/products/${item.slug}`}><div className="card-top"><span className={illustrationStyles.catalogArt}>{item.image?<img src={item.image} alt={item.name} width={84} height={84} loading="lazy" style={{width:"100%",height:"100%",objectFit:"contain"}}/>:<IllustrationImage candidates={productIllustrations(item)} sizes="84px"/>}</span><span className="mini-label">{markets.length?markets.join(' · '):item.category}</span></div><div className="product-title-row"><h3>{item.name}</h3>{item.status==='draft'&&<span className="preview-pill">Preview</span>}</div>{item.content.aliases?.length?<span className="product-aliases">Also searched as {item.content.aliases.slice(0,3).join(', ')}</span>:null}<p>{item.summary}</p><div className="card-bottom"><span>{item.status==='draft'?'Review landing page':'Explore product'}</span><span className="card-plus" aria-hidden="true">+</span></div></a>}
export function Catalog({items,compact=false}:{items:CatalogCard[];compact?:boolean}){const [query,setQuery]=useState('');const [market,setMarket]=useState('All markets');const [category,setCategory]=useState('All categories');const markets=['All markets',...Array.from(new Set(items.flatMap(r=>(r.content.catalogPlacements||[]).map(p=>p.market))))];const marketCategories=Array.from(new Set(items.flatMap(r=>(r.content.catalogPlacements||[]).filter(p=>market==='All markets'||p.market===market).map(p=>p.category))));const filtered=items.filter(r=>{const placements=r.content.catalogPlacements||[];const marketMatch=market==='All markets'||placements.some(p=>p.market===market);const categoryMatch=category==='All categories'||placements.some(p=>(market==='All markets'||p.market===market)&&p.category===category);const searchText=`${r.name} ${r.category} ${r.summary} ${(r.content.aliases||[]).join(' ')} ${placements.map(p=>`${p.market} ${p.category}`).join(' ')}`;return marketMatch&&categoryMatch&&searchText.toLowerCase().includes(query.toLowerCase())});const shown=compact&&query===''&&market==='All markets'&&category==='All categories'?filtered.slice(0,6):filtered;return <div className="catalog"><div className="catalog-toolbar"><label className="search-field"><Search size={20}/><input aria-label="Search products" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products, aliases, markets, or categories"/><kbd>⌕</kbd></label><span className="catalog-count"><SlidersHorizontal size={16}/>{filtered.length} products</span></div><div className="catalog-filter-group"><span>Market</span><div className="category-tabs" aria-label="Filter by market">{markets.map(m=><button type="button" aria-pressed={market===m} className={market===m?'selected':''} key={m} onClick={()=>{setMarket(m);setCategory('All categories')}}>{m}</button>)}</div></div>{marketCategories.length>0&&<div className="catalog-filter-group"><span>Category</span><div className="category-tabs secondary" aria-label="Filter by category">{['All categories',...marketCategories].map(c=><button type="button" aria-pressed={category===c} className={category===c?'selected':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>}{shown.length?<div className="product-grid">{shown.map(r=><ProductCard item={r} key={r.id}/>)}</div>:<div className="empty-state"><h3>No matching products.</h3><p>Try a different search, or tell us what you need.</p><a href="/request" className="button dark">Request sourcing</a></div>}{compact&&shown.length<filtered.length&&<div className="catalog-more"><a href="/products" className="button outline">Browse the full directory</a></div>}</div>}
