import {ProductPostcards} from './product-postcards';
import type {Post,Content,Product} from '@/lib/types';
import {ProductCard} from './catalog';
export function PostCard({post,index=0}:{post:Post;index?:number}){return <a className="post-card" href={`/insights/${post.slug}`}><div className={`post-cover cover-${index%3}`}>{post.image?<img src={post.image} alt="Illustrative wood sourcing scene" loading="lazy"/>:<><span className="cover-label">THE SOURCING JOURNAL</span><span className="cover-number">0{index+1}</span><span className="cover-topic">{index%3===1?'THE PRODUCT BRIEF':'THE BUYER’S NOTE'}</span></>}</div><div className="post-meta"><span>{post.category}</span><span>{Math.max(3,Math.ceil(post.content.sections.reduce((n,s)=>n+s.paragraphs.join(' ').split(' ').length,0)/200))} min read</span></div><h3>{post.title}</h3><p>{post.summary}</p><span className="read-link">Read the guide</span></a>}
export function ContentBody({content,products=[]}:{content:Content;products?:Product[]}){function textWithLinks(text:string){const sorted=[...products].sort((a,b)=>b.name.length-a.name.length);if(!sorted.length)return text;const regex=new RegExp(`(${sorted.map(i=>i.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')})`,'gi');return text.split(regex).map((part,i)=>{const item=sorted.find(r=>r.name.toLowerCase()===part.toLowerCase());return item?<a key={i} href={`/products/${item.slug}`}>{part}</a>:part;});}return <div className="prose">{content.sections.map((s,i)=><section id={`section-${i}`} key={i}><h2>{s.heading}</h2>{s.paragraphs.map((p,j)=><p key={j}>{textWithLinks(p)}</p>)}</section>)}{content.buyingChecklist.length>0&&<section className="checklist"><span className="eyebrow">BEFORE YOU REQUEST</span><h2>Your sourcing checklist.</h2><ul>{content.buyingChecklist.map(p=><li key={p}>{p}</li>)}</ul></section>}{content.faqs.length>0&&<section><h2>Common questions.</h2><div className="faq-list">{content.faqs.map((f,i)=><details key={f.question}><summary>{f.question}<span>+</span></summary><p>{f.answer}</p></details>)}</div></section>}</div>}
export function RelatedProducts({items}:{items:Product[]}){return <ProductPostcards items={items} eyebrow="EXPLORE PRODUCTS"/>;}
export function SourcingCTA(){return <section className="sourcing-banner"><div><span className="eyebrow">YOUR NEXT SUPPLY CONVERSATION</span><h2>Tell us what you’re sourcing.</h2><p>One clear brief. The right details. A more useful broker conversation.</p></div><a href="/request" className="button lime">Request a quote</a></section>}

export function ImageCredit({credit}:{credit:string}){const [name,url]=credit.split(" · ");return <figcaption>{name}{url&&url.startsWith("https://www.pexels.com/")&&<> · <a href={url} target="_blank" rel="noopener noreferrer">View on Pexels</a></>}</figcaption>;}
