'use client';
import {useEffect,useState} from 'react';
import {Plus,RefreshCw,Save} from 'lucide-react';
import type {Lead} from '@/lib/types';
import {BrokerExport} from './broker-export';

type Partner={id:string;name:string;contact:string;email:string;phone:string;location:string;notes:string;active:number};
type Row=Record<string,string|number|null>;
type Workspace={partners:Partner[];lots:Row[];deals:Row[];products:{slug:string;name:string}[];leads:Lead[]};
const blank:Workspace={partners:[],lots:[],deals:[],products:[],leads:[]};
const units=['Board feet','Linear feet','Square feet','Sheets','Slabs','Pieces','Truckloads'];
const stages=['new','qualified','supplier-review','quote-ready','customer-review','invoiced','paid','shipped','delivered','closed','lost'];
const partnerDraft={kind:'partner',name:'',contact:'',email:'',phone:'',location:'',notes:'',active:true};
type Draft=Record<string,string|number|boolean|null>;
export function WoodWorkspace({onDirtyChange}:{onDirtyChange:(dirty:boolean)=>void}){
 const [data,setData]=useState(blank),[tab,setTab]=useState('deals'),[draft,setDraft]=useState<Draft|null>(null),[baseline,setBaseline]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const dirty=!!draft&&JSON.stringify(draft)!==baseline;
 useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
 async function load(){const response=await fetch('/api/admin/wood',{cache:'no-store'});const body=await response.json() as Workspace & {error?:string};if(!response.ok)throw new Error(body.error||'Could not load sourcing records.');setData(body);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const open=(next:Draft|null)=>{if(dirty&&!confirm('Discard unsaved changes?'))return;setDraft(next);setBaseline(JSON.stringify(next));setError('');setNotice('');};
 const patch=(key:string,value:string|number|boolean|null)=>setDraft(d=>d?{...d,[key]:value}:d);
 const field=(key:string,label:string,type='text',required=false)=><label className="field"><span>{label}</span><input required={required} type={type} min={type==='number'?0:undefined} step={type==='number'?'any':undefined} value={String(draft?.[key]??'')} onChange={e=>patch(key,type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/></label>;
 const select=(key:string,label:string,options:{value:string;label:string}[],empty?:string)=><label className="field"><span>{label}</span><select required={!empty} value={String(draft?.[key]||'')} onChange={e=>patch(key,e.target.value||null)}>{empty&&<option value="">{empty}</option>}{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
 const options=(values:string[])=>values.map(value=>({value,label:value.replaceAll('-',' ')}));
 const partnerOptions=data.partners.map(p=>({value:p.id,label:p.name+(p.active?'':' (inactive)')}));
 function newLot(){open({kind:'lot',productSlug:data.products[0]?.slug||'',partnerId:data.partners.find(p=>p.active)?.id||'',reference:'',quantity:null,unit:'Board feet',dimensions:'',condition:'',location:'',status:'unconfirmed',notes:''});}
 function editLot(row:Row){open({kind:'lot',id:row.id,productSlug:row.product_slug,partnerId:row.partner_id,reference:row.reference,quantity:row.quantity,unit:row.unit,dimensions:row.dimensions,condition:row.condition,location:row.location,status:row.status,notes:row.notes});}
 function editDeal(lead:Lead){const row=data.deals.find(d=>d.lead_id===lead.id);open({kind:'deal',leadId:lead.id,partnerId:row?.partner_id||null,stage:row?.stage||'new',materialAmount:row?.material_amount??null,freightAmount:row?.freight_amount??null,commissionAmount:row?.commission_amount??null,commissionPaid:!!row?.commission_paid_at,quoteExpires:row?.quote_expires||'',invoiceReference:row?.invoice_reference||'',shipmentReference:row?.shipment_reference||'',trackingUrl:row?.tracking_url||'',notes:row?.notes||''});}
 async function save(event:React.FormEvent){event.preventDefault();if(!draft||busy)return;setBusy(true);setError('');try{const response=await fetch('/api/admin/wood',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const result=await response.json() as {id:string;error?:string};if(!response.ok)throw new Error(result.error||'Save failed.');const saved={...draft,...(draft.kind==='deal'?{}:{id:result.id})};setDraft(saved);setBaseline(JSON.stringify(saved));await load();setNotice('Saved.');}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 const lead=draft?.kind==='deal'?data.leads.find(l=>l.id===draft.leadId):undefined;
 return <div className="wood-workspace"><header className="section-heading"><div><span className="eyebrow">RAREWOOD OPERATIONS</span><h1>From inquiry to delivery.</h1><p>Supplier relationships, confirmed lots, quotes, and commissions.</p></div><button className="button outline" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={16}/> Refresh</button></header>
 <div className="category-tabs">{[['deals','Quotes & fulfillment'],['partners','Supply partners'],['lots','Inventory lots']].map(([key,label])=><button key={key} aria-pressed={tab===key} className={tab===key?'selected':''} onClick={()=>{if(dirty&&!confirm('Discard unsaved changes?'))return;setTab(key);setDraft(null);setBaseline('');}}>{label}</button>)}</div>
 {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="wood-operations-grid"><section className="wood-record-list">
 {tab==='partners'&&<><button className="button dark" onClick={()=>open({...partnerDraft})}><Plus size={16}/> Add supply partner</button>{data.partners.map(p=><button className="wood-record" key={p.id} onClick={()=>open({...p,kind:'partner',active:!!p.active})}><strong>{p.name}</strong><span>{p.contact} · {p.location}</span><small>{p.active?'Active':'Inactive'}</small></button>)}</>}
 {tab==='lots'&&<><button className="button dark" onClick={newLot} disabled={!data.partners.length}><Plus size={16}/> Add inventory lot</button><p>Only available lots confirmed within seven days appear on product pages. Record actual quantities after supplier confirmation.</p>{data.lots.map(row=><button className="wood-record" key={String(row.id)} onClick={()=>editLot(row)}><strong>{row.reference}</strong><span>{data.products.find(p=>p.slug===row.product_slug)?.name} · {row.quantity??'Quantity unconfirmed'} {row.quantity!==null?row.unit:''}</span><small>{row.status}{row.confirmed_at?` · confirmed ${String(row.confirmed_at).slice(0,10)}`:''}</small></button>)}{!data.lots.length&&<p className="empty-state">No inventory has been claimed or imported.</p>}</>}
 {tab==='deals'&&<>{data.leads.map(l=>{const d=data.deals.find(r=>r.lead_id===l.id);return <button className="wood-record" key={l.id} onClick={()=>editDeal(l)}><strong>{l.product}</strong><span>{l.company} · {l.reference}</span><small>{String(d?.stage||'new').replaceAll('-',' ')}</small></button>;})}{!data.leads.length&&<div className="empty-state"><h3>A clean sourcing inbox.</h3><p>New buyer requests will appear here. Select a request to assign a partner, record a quote, and track fulfillment.</p><a href="/request" className="text-link" target="_blank" rel="noreferrer">View inquiry form</a></div>}</>}
 </section><section className="wood-record-editor">{draft?<form onSubmit={save}><h2>{draft.kind==='partner'?'Supply partner':draft.kind==='lot'?'Inventory lot':lead?.product||'Sourcing record'}</h2>
 {draft.kind==='partner'&&<><div className="form-grid">{field('name','Business name','text',true)}{field('contact','Contact name')}</div><div className="form-grid">{field('email','Email','email')}{field('phone','Phone','tel')}</div>{field('location','Location')}<label className="consent-field"><input type="checkbox" checked={!!draft.active} onChange={e=>patch('active',e.target.checked)}/> Active sourcing partner</label></>}
 {draft.kind==='lot'&&<>{select('productSlug','Product',data.products.map(p=>({value:p.slug,label:p.name})))}{select('partnerId','Supply partner',partnerOptions)}{field('reference','Supplier lot reference','text',true)}<div className="form-grid">{field('quantity','Available quantity','number')}{select('unit','Quantity unit',options(units))}</div>{field('dimensions','Actual dimensions, lengths, or profile')}{field('condition','Grade, surface, and moisture condition')}{field('location','Inventory location')}{select('status','Availability',options(['unconfirmed','available','reserved','sold','withdrawn']))}<p className="secondary-text">Saving as available confirms this quantity as of today. Unconfirmed, reserved, sold, and stale lots stay private.</p></>}
 {draft.kind==='deal'&&<>{lead&&<div className="wood-inquiry-brief"><b>{lead.company} · {String(lead.payload.name||'')}</b><p>{lead.email} · {String(lead.payload.phone||'')}</p><p>{String(lead.payload.volume||'')} {String(lead.payload.unit||'')} · {String(lead.payload.destination||'')}</p><p>{String(lead.payload.dimensions||lead.payload.grade||'')} · {String(lead.payload.timing||'')}</p><BrokerExport kind="buyer" lead={lead}/></div>}{select('partnerId','Assigned supply partner',partnerOptions,'Not assigned')}{select('stage','Deal stage',options(stages))}<div className="form-grid">{field('materialAmount','Supplier material quote · USD','number')}{field('freightAmount','Freight quote · USD','number')}</div><div className="form-grid">{field('commissionAmount','Agreed commission · USD','number')}{field('quoteExpires','Quote valid through','date')}</div><label className="consent-field"><input type="checkbox" checked={!!draft.commissionPaid} onChange={e=>patch('commissionPaid',e.target.checked)}/> Commission received</label>{field('invoiceReference','Supplier invoice reference')}{field('shipmentReference','Freight / Warp reference')}{field('trackingUrl','Shipment tracking URL','url')}<p className="secondary-text">Record supplier-confirmed terms here. Payments, freight bookings, and tracking updates are handled externally; this workspace does not charge customers or book shipments.</p></>}
 <label className="field"><span>Private notes</span><textarea rows={5} maxLength={4000} value={String(draft.notes||'')} onChange={e=>patch('notes',e.target.value)}/></label><button className="button dark" disabled={busy} type="submit"><Save size={16}/>{busy?'Saving…':'Save record'}</button></form>:<div className="empty-state"><h2>Select a record.</h2><p>Your sourcing details stay private in the admin workspace.</p></div>}</section></div></div>;
}
