from pathlib import Path
import json,re
root=Path(__file__).resolve().parents[1]
def save(p,v): (root/p).write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
def slug(s):return re.sub('[^a-z0-9]+','-',s.lower()).strip('-')
names=['Purpleheart','Wenge','Zebrawood','Sapele','African Mahogany','Honduran Mahogany','Bolivian Rosewood','Padauk','Iroko','Canarywood','Bubinga','Red Grandis','Bloodwood','Kabukalli','Itauba','Jatoba','Utile','Spanish Cedar','Ipe','Cumaru','Curupixa','Guatambu','Cerejeira','Japanese Cedar','Garapa','Massaranduba','Timborana','Tigerwood','Yellowheart','Angelim','Cachichira','Birch','Baltic Birch','Meranti','Maple','Walnut']
aliases={'Bolivian Rosewood':['Morado','Pau Ferro','Santos Rosewood'],'Jatoba':['Brazilian Cherry'],'Ipe':['Brazilian Walnut','Lapacho'],'Cumaru':['Brazilian Teak'],'Utile':['Sipo'],'Japanese Cedar':['Sugi'],'Zebrawood':['Zebrano'],'Purpleheart':['Purple Heart'],'Tigerwood':['Goncalo Alves'],'Bloodwood':['Blood Wood'],'Guatambu':['Brazilian Maple'],'Massaranduba':['Masaranduba','Macaranduba']}
forms={'Exotic lumber':('lumber','Board feet','Furniture & millwork','State rough or surfaced condition, required finished thickness, widths and usable lengths. A nominal board size does not describe its finished dimensions.',['Rough or surfaced condition','Thickness, width and length requirements','Grade, defects and acceptable variation']), 'Hardwood decking':('decking','Linear feet','Exterior decking','Board width, thickness, length mix and edge profile determine how a decking order is priced and installed. Specify grooved or square-edge boards and share the fastening plan.',['Board dimensions and length schedule','Square or grooved edges','Fastening system and intended exposure']), 'Hardwood flooring':('flooring','Square feet','Interior flooring','Coverage, profile and usable lengths matter when matching flooring to a room. Identify finished or unfinished material and compare face width, thickness and the length mix.',['Required coverage and waste allowance','Thickness, face width and profile','Finished or unfinished surface']), 'Slabs & rounds':('slabs','Slabs','Tables & countertops','Each slab is an individual piece. Measurements at the narrowest usable width, thickness after flattening, visible checks and edge condition help determine whether it fits the project.',['Minimum usable width and length','Thickness and flattening requirements','Photos of both faces and visible defects']), 'Plywood & panels':('plywood','Sheets','Cabinetry & interiors','Face species alone does not describe a plywood panel. Core construction, actual thickness, sheet size and face finish are separate specifications to include in the request.',['Actual thickness and sheet dimensions','Face and back grade, core construction','Finished faces and intended use'])}
products=[]
for name in names[:24]:products.append((name,'Exotic lumber'))
for name in ['Ipe','Garapa','Massaranduba']:products.append((name,'Hardwood decking'))
for name in ['Timborana','Ipe','Jatoba','Bloodwood']:products.append((name,'Hardwood flooring'))
for name in ['Ipe','Jatoba','Tigerwood','Cumaru','Yellowheart','Angelim','Itauba','Timborana','Cachichira','Bolivian Rosewood']:products.append((name,'Slabs & rounds'))
for name in ['Birch','Baltic Birch','Meranti','Maple','Walnut']:products.append((name,'Plywood & panels'))
catalog=[];records=[];now='2026-10-07T17:43:00.000Z'
for species,category in products:
 form,unit,use,description,checklist=forms[category];name=f'{species} {"Slabs" if form=="slabs" else form.title()}';key=slug(name)
 pending=species=='Cachichira';status='draft' if pending else 'published';source_status='proposed' if pending else 'current'
 summary=f'{species} {form} for {use.lower()}. Compare dimensions, material condition and order requirements, then request current pricing for your project.'
 requirements=checklist+['Order quantity and unit','Delivery ZIP, timing and unloading access']
 topics=[{'slug':key+'-'+s,'title':t,'intent':intent,'targetKeyword':kw,'brief':brief} for s,t,intent,kw,brief in [
 ('dimensions-and-specifications',f'{name}: dimensions and specifications to compare','specification',f'{name} dimensions and specifications',f'Explain the specific measurements and condition checks that distinguish {name.lower()} offers. Cover {", ".join(checklist).lower()}. Avoid invented grades or stock claims. Link to /products/{key} for a quote.'),
 ('project-planning',f'Planning a project with {name.lower()}','application',f'{name} project planning',f'Explain how project requirements affect the selection of {name.lower()} for {use.lower()}. Discuss useful allowances, design constraints and alternatives without asserting engineering ratings. Link back to /products/{key}.'),
 ('shipping-and-receiving',f'{name} delivery: preparing to receive an order','logistics',f'{name} shipping and receiving',f'Explain how packaged size, unloading access and receiving conditions affect a shipment of {name.lower()}. Distinguish freight estimates from final supplier terms. Do not invent weight, rates or handling limits. Link to /products/{key}.')]]
 faqs=[{'question':f'How do I request a price for {name.lower()}?','answer':f'Include the dimensions, quantity in {unit.lower()}, intended use and destination ZIP. Those details allow material and delivery costs to be quoted for the same requirement.'},{'question':'Can I review the actual material before ordering?','answer':'Ask for current lot photographs and a written description of dimensions, condition and any defects. For an individual slab, request images of both faces and measurements of its usable area.'},{'question':'Who confirms availability and takes payment?','answer':'The selected supplier confirms the material and commercial terms, issues the customer invoice and receives payment. Rarewood Exchange coordinates the sourcing inquiry and may earn a commission on a completed sale.'}]
 overview=[f'{name} is one of the wood product forms available for sourcing through Rarewood Exchange. {description}',f'A request for {species.lower()} should identify the product form as well as the species. The written quote should specify the actual material, measured dimensions, condition, quantity and delivery terms so the offered lot can be compared with your project requirements.']
 profile={'displayName':name,'badges':[category,'Quote by requirement'],'facts':[{'label':'Product type','value':category},{'label':'Primary use','value':use},{'label':'Physical forms','value':form.title()}],'highlights':requirements,'overview':overview,'benefits':[{'title':'Dimensions that fit', 'text':description},{'title':'Material condition','text':f'Assess the offered {species.lower()} by its actual condition. Surface preparation, visible defects and usable dimensions influence the material available for the finished project.'}],'specifications':{'caption':'Details to include in a product quote','columns':['Characteristic','What to specify'],'rows':[[checklist[0],description],[checklist[1],'Describe the requirement and any acceptable alternatives.'],['Quantity',f'Use {unit.lower()} for this product form and attach a cut list where available.'],['Material condition','Request actual lot photographs, disclosed defects and measured moisture information when relevant.']],'note':'Specifications, quantity and availability are confirmed for the offered material in the supplier quote.'},'applications':[{'title':use,'text':f'Share the dimensions and material requirements for your {use.lower()} project. The supplier can identify which offered pieces or lots match those requirements.'}],'shipping':[{'title':'Define the order','text':f'Include the required {name.lower()} dimensions, quantity in {unit.lower()}, destination ZIP and target date. Identify any acceptable alternative sizes.'},{'title':'Confirm freight and unloading','text':'The supplier confirms packaged dimensions, weight and pickup readiness. Delivery planning includes truck access, a dock or forklift, appointment requirements and any special unloading arrangements.'},{'title':'Receive and inspect','text':'Check the delivered pieces against the written order and document visible damage before signing delivery paperwork. Follow the supplier’s handling, storage and acclimation guidance for the material and its intended use.'}],'related':[],'faqs':faqs}
 content={'seoTitle':f'{name} — Pricing & Sourcing | Rarewood Exchange','seoDescription':summary[:195],'sections':[{'heading':f'Buying {name.lower()}','paragraphs':overview}],'applications':[use],'buyingChecklist':requirements,'faqs':faqs,'relatedProducts':[],'sourceNotes':'','aliases':aliases.get(species,[]),'catalogPlacements':[{'market':'Wood products','category':category}],'sourceStatus':source_status,'needsClarification':pending,'customLayout':True,'landingProfile':profile,'blogTopics':topics,'tags':[species,form.title()],'topics':[use],'speciesSlug':slug(species),'wood':{'form':form,'unit':unit,'availability':'quote-required'},'generationState':'ready'}
 records.append({'id':'wood-'+key,'slug':key,'name':name,'category':category,'summary':summary,'content':content,'image':'','imageCredit':'','status':status,'createdAt':now,'updatedAt':now})
 catalog.append({'slug':key,'name':name,'category':category,'summary':summary,'aliases':aliases.get(species,[]),'placements':content['catalogPlacements'],'sourceStatus':source_status,'needsClarification':pending})
for r in records:
 peers=[x['slug'] for x in records if x['category']==r['category'] and x['slug']!=r['slug'] and x['status']=='published'][:4]
 r['content']['relatedProducts']=peers;r['content']['landingProfile']['related']=peers
save('data/wood-products.json',records);save('data/imported-catalog.json',catalog)
species=[{'slug':slug(n),'name':n,'aliases':aliases.get(n,[]),'summary':f'Explore {n.lower()} by product form. Compare relevant lumber, decking, flooring or slab pages and request a quote for your required dimensions.','status':'draft' if n=='Cachichira' else 'published'} for n in names if any(r[0]==n for r in products)]
save('data/wood-species.json',species)
save('data/catalog-taxonomy.json',{'markets':[{'market':'Wood products','categories':[{'category':c} for c in forms]}],'seoModifiers':{'buying':['lumber','wholesale','specialty hardwood','slabs','decking','flooring','plywood','delivered quote','board feet']}})
save('data/illustrations/runtime.json',{'asset_base':'/images/wood','generic_image_id':'lumber-engraving','families':{'lumber-engraving':{'alt':'Illustration of hardwood boards and a live-edge slab','status':'ready','width':640,'height':640}},'categories':{c:'lumber-engraving' for c in forms},'record_assignments':{},'slug_assignments':{}})
print(f'{len(records)} product guides, {len(species)} species, {sum(x["status"]=="published" for x in records)} publishable guides; no inventory quantities or prices imported.')
